name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: label-t2
    steps:
      - run: echo "Hello, world!"

  test:
    runs-on: label-t2
    steps:
      - run: echo "Running tests..."

  prod:
    runs-on: label-t3
    steps:
      - run: echo "Running prod..."
